### ISSUE TITLE
Query results out of order in 0.4.3+

### ISSUE THREAD

**Issue by richardonrails** [mixonic/ranked-model#146]
I had a line of code like:

```rb
@categories = model.categories.rank(:row_order).includes(:articles).merge(scoped_articles).references(:articles)
```

On 0.4.2 it returned categories in the expected ranked order.
However on 0.4.3-0.4.4 the order is no longer correct.

However I noticed that it does work in the later version if I move the `rank()` to the end:

```rb
@categories = model.categories.includes(:articles).merge(scoped_articles).references(:articles).rank(:row_order)
```

Would you consider this a regression? Or does rank() always need to be at the end like that?

**Comment by brendon** [comment]
Hi @richardonrails, the code for the `rank` scope is just:

```
      scope :rank, lambda { |name|
        reorder ranker(name.to_sym).column
      }
```

Things might be coming unstuck with `reorder`. I changed it here: https://github.com/mixonic/ranked-model/commit/ab5a57e59e4a72ddd424aa6757c30e90dc35cb1d

This wipes out other orders set prior. Can you do some digging to see if you're setting other orders that you would have rather seen merged instead of wiped? It's a bit of a tricky one.

`ancestry` has the concept of `ordered_by_ancestry_and()` as a way around this. Perhaps we could come up with something similar? But let's see what you find first.

**Comment by richardonrails** [comment]
I'm doing something like this:

```
@categories = model.categories.rank(:row_order).includes(:articles).merge(articles.rank(:row_order)).references(:articles)
```

So while there is another ordering involved in this line of code -- it is for the articles rather than the categories. Not sure if that answers your question...

**Comment by brendon** [comment]
Hi @richardonrails, it would definitely make a difference. SQL only allows for one `ORDER BY` clause as far as I'm aware, so when you use multiple rails `order()`'s it joins them together. Because we switched to using `reorder()` instead of `order()` earlier order clauses get thrown out and the last one takes effect. Are you wanting to have categories ordered by their position, then the related articles also ordered by the article's position within? If not, just omit the rank on articles and the other one will flow through. If so, you might need to not use `rank()` and instead use a custom `order('categories.row_order', 'articles.row_order')`.

**Comment by richardonrails** [comment]
> Are you wanting to have categories ordered by their position, then the related articles also ordered by the article's position within?

Yes, exactly.

> If so, you might need to not use rank() and instead use a custom `order('categories.row_order', 'articles.row_order')`.

Okay, this works (although in my case I am using a custom `reorder` instead of `order`, since typically I want `scoped_articles` to contain an order already, which I'm now replacing because of the JOIN)

Thanks!

**Comment by brendon** [comment]
You're welcome :) If you can see any way that we can make things work better from within `ranked_model` please do feel free to submit a PR or add more to this issue :D
