### ISSUE TITLE
How to make it work with ancestry?

### ISSUE THREAD

**Issue by npearson72** [mixonic/ranked-model#91]
I'd like to sort child categories within their parents. I use the ancestry gem for generating categories.

Would ranked-model play well with it? If so, how would I go about setting the scope for sorting within parent categories?

Also, do you tell it which position to use if you were to move a category from say.. the bottom of the list to the middle somewhere?

**Comment by brendon** [comment]
It looks like you can just do the following:

```ruby
ranks :row_order, with_same: [:ancestry]
```

I've included an array there because you may want to add other constraints such as a `belongs_to` association.

However, I'm currently having trouble using the `:up` and `:down` values for reordering! :) But the scoping seems to work properly at least :)

**Comment by npearson72** [comment]
Great, thank you.
